### ISSUE TITLE
Integration with Simple Difficulty

### ISSUE THREAD

**Issue by Fox0B0t** [Tiviacz1337/Travelers-Backpack-Integration#1]
Hi, first I'd like to say thanks for your work porting and maintaining the mod, I made a GitHub account just to post here.

I would like to request integration with Simple Difficulty, one of the many successors of Tough as Nails, and my choice given the later's discontinuation.

Link to the mod to save you some clicks: https://www.curseforge.com/minecraft/mc-mods/simpledifficulty

Once again, thanks for your work.

**Comment by Tiviacz1337** [comment]
Hi, thanks for kind words. I'd like to know how integration between Traveler's Backpack and Simple Difficulty would look like. I don't know this mod, so if you could make a quick description of integration, I'd be glad.

**Comment by Fox0B0t** [comment]
You're welcome. Simple Difficulty is just Tough as Nails with a re-skin and a somewhat active development, so I was hoping you would allow the transfer of Purified Water from bottles to the tanks and vice-versa at the very least.
Attached goes a screenshot with the item ID.
![2020-07-07_23 26 49](https://user-images.githubusercontent.com/67982819/86867977-2e2e9700-c0aa-11ea-8ad4-bccee26edcea.png)

Thanks for the quick reply.

**Comment by Fox0B0t** [comment]
Regrettably I don't know anything about coding, but I'll try to be as helpful as I am able.

**Comment by Tiviacz1337** [comment]
That's okay, I don't ask about coding just want to know what integrations would you like to see. 

> allow the transfer of Purified Water from bottles to the tanks and vice-versa
Done

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-integrations/files/3000409
