### ISSUE TITLE
Suggestion: Tetra tool integration

### ISSUE THREAD

**Issue by FSwordFoxA** [Tiviacz1337/Travelers-Backpack-Integration#3]
See title. Tested with the 1.15 versions of Traveler's Backpack and Tetra.

The Traveler's Backpack by itself doesn't recognize tools made in Tetra's worktable as a valid tool. You can't put them in the backpack's tool slots as a result. Or at least it wouldn't let me out them in those tool slots. So if a 1.15 version of this integration mod does end up on the to-do list, Tetra integration would be nice.

**Comment by Tiviacz1337** [comment]
This feature is in Traveler's Backpack itself, but niy in 1.14.4, 1.15.2, 1.16
